// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS8V6m6LPSudMgQvdUQPEfvzvj8tfbnok',
    appId: '1:977101323430:web:37b682162707f24c984867',
    messagingSenderId: '977101323430',
    projectId: 'mini-projet-l3-e1886',
    authDomain: 'mini-projet-l3-e1886.firebaseapp.com',
    storageBucket: 'mini-projet-l3-e1886.firebasestorage.app',
    measurementId: 'G-MZMNM8T1XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTGHjApM0E7k-VX-wZxYnyqTLCd5zecBw',
    appId: '1:977101323430:android:96098c6e609e0e68984867',
    messagingSenderId: '977101323430',
    projectId: 'mini-projet-l3-e1886',
    storageBucket: 'mini-projet-l3-e1886.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVl-4lY2Wf7dPOVtHZliEyqVbuHbdpJL8',
    appId: '1:977101323430:ios:f29bacc134847fa2984867',
    messagingSenderId: '977101323430',
    projectId: 'mini-projet-l3-e1886',
    storageBucket: 'mini-projet-l3-e1886.firebasestorage.app',
    iosBundleId: 'com.example.flutterBackend1',
  );
}
